### ISSUE TITLE
[WIP] Predicate Logic Notation

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-predicates#31]
[New version is here.](https://github.com/cryptoeconomicslab/plasma-predicates/issues/41)

## Overview

Define the notation of predicate to make discussion more efficiently.
@tkmct @shogochiai 

## What problem can be solved

It's hard to explain new predicate each time is created. Researchers need very high context background to understand the behavior of deprecation logic in the discussion. ex) [plasma.build](https://plasma.build/t/fast-finality-predicate/79/4) We define the notation for predicates to define and share a new predicate quickly and correctly.

## How does it work in detail

We will provide more abstract ways to express predicates than Solidity.

### Structure

TODO: better to use the language to define scheme.

```
state:
  transitions:
   condition: the condition of deprecation
   next: next state update
```

* `data` is `StateObject.data`
* `params` is `transaction.parameters`
* `otherwise` means "after extra dispution period"

### Examples

notice: we didn't decide to use YAML, this is just examples.

```yaml

 # SimpleOwnership
 ownership:
   condition:
   	sig: data.owner
   next:
   	params.stateUpdate
 
 # Simple Swap which specify counter StateUpdate
 simple_swap:
 	transitions:
 	- condition:
 	    and:
 	    - inclusion: data.correspondingStateUpdate
 	    - or:
              - finalizeExit: data.correspondingStateUpdate
              - proveDeprecation: data.correspondingStateUpdate
 	    - sig: data.nextOwner
 	  next: params.stateUpdate
 	- condition:
 	    and:
 	    - otherwise(Must wait extra dispution period?)
 	    - sig: data.prevOwner
 	  next: params.stateUpdate
 
 # Swap which specifies token amount and token address
 swap_specify_token_type:
 	transitions:
 	- condition:
 	    and:
 	    - checkpoint: params.correspondingStateUpdate
 	    - sig: params.correspondingStateUpdate.owner
 	    - eq: token(params.correspondingStateUpdate), token(data.order) # it would be bettr to use programming language
 	  next: params.stateUpdate
 	- condition:
 	    and:
 	    - otherwise
 	    - sig: data.prevOwner
 	  next: params.stateUpdate
 ```

## What topic to research next

* How do we define except deprecation model?
* How do we define initiation exit condition?
* How do we verify security?
