### ISSUE TITLE
Add document of simple swap predicate

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-predicates#32]
## Is your feature request related to a problem? Please describe.

There are no implementations of swap predicate.

## Describe the solution you'd like

Write simple swap predicate. Simple swap is the swap which specifies certain correspondent StateUpdate.

```yaml
 # Simple Swap is the swap specifies correspondent StateUpdate
 simple_swap:
 	transitions:
 	- condition:
 	    and:
 	    - inclusion: data.correspondingStateUpdate
 	    - or:
              - finalizeExit: data.correspondingStateUpdate
              - proveDeprecation: data.correspondingStateUpdate
 	    - sig: data.nextOwner
 	  next: params.stateUpdate
 	- condition:
 	    and:
 	    - otherwise(Must wait extra dispution period?)
 	    - sig: data.prevOwner
 	  next: params.stateUpdate
```

## Describe alternatives you've considered

Use PG's core predicates?

## Additional context

https://plasma.build/t/a-question-about-verify-deprecation/41/3
notation: https://github.com/cryptoeconomicslab/plasma-predicates/issues/31
